version: '2'

services:
  mqtt:
    container_name: monitor-mqtt
    image: eclipse-mosquitto
    volumes:
      - data:/mosquitto/data
    ports:
      - 1883:1883

  influxdb:
    container_name: monitor-influxdb
    image: influxdb:alpine
    volumes:
      - data:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_GRAPHITE_ENABLED: "true"

  grafana:
    container_name: monitor-grafana
    image: grafana/grafana
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  data:
    external:
      name: monitor-data


