version: '2'

services:
  mqtt:
    container_name: monitor-mqtt
    image: eclipse-mosquitto
    volumes:
      - data:/mosquitto/data
    ports:
      - 1883:1883

  gateway:
    container_name: monitor-gateway
    image: jfloff/alpine-python:3.4-slim
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./bc-gateway.py:/usr/src/app/bc-gateway.py
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    links:
      - mqtt
    depends_on:
      - mqtt
    command:
      - "python /usr/src/app/bc-gateway.py -W -d /dev/ttyACM0 -h mqtt"

  influxdb:
    container_name: monitor-influxdb
    image: influxdb:alpine
    volumes:
      - data:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_GRAPHITE_ENABLED: "true"

  mqtt_to_influxdb:
    container_name: monitor-mqtt_to_influxdb
    image: jfloff/alpine-python:3.4-slim
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./bc-mqtt-to-influxdb.py:/usr/src/app/bc-mqtt-to-influxdb.py
    links:
      - mqtt
      - influxdb
    depends_on:
      - mqtt
      - gateway
      - influxdb
    command:
      - "python /usr/src/app/bc-mqtt-to-influxdb.py -h mqtt --influxdb-host influxdb"

  grafana:
    container_name: monitor-grafana
    image: grafana/grafana
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  data:
    external:
      name: monitor-data


